name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mrvinkel-adify-service"
          heroku_email: "martin.valsgaard.vinkel@beumergroup.com"

      - name: Slow test
        run: mvn test -DskipTests=false -Dgroups=slow

      - name: Merge release
        run: |
          git checkout ${GITHUB_REF#refs/heads/}
          git rebase origin/release
          git branch release
          git push origin release:release